version: '3.8'

services:
  app:
    image: your-docker-repo/kafka-template:latest
    ports:
      - "8080:8080"
    environment:
      BUSINESS_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      BUSINESS_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      BUSINESS_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EVENT_DATASOURCE_URI: ${SPRING_DATA_MONGODB_URI}
      EVENT_DATASOURCE_DATABASE: ${SPRING_DATA_MONGODB_DATABASE}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_CONSUMER_GROUP_ID: ${KAFKA_CONSUMER_GROUP_ID}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET}
      KAFKA_CONSUMER_KEY_DESERIALIZER: ${KAFKA_CONSUMER_KEY_DESERIALIZER}
      KAFKA_CONSUMER_VALUE_DESERIALIZER: ${KAFKA_CONSUMER_VALUE_DESERIALIZER}
      KAFKA_PRODUCER_KEY_SERIALIZER: ${KAFKA_PRODUCER_KEY_SERIALIZER}
      KAFKA_PRODUCER_VALUE_SERIALIZER: ${KAFKA_PRODUCER_VALUE_SERIALIZER}
      ELASTICSEARCH_CLUSTER_NAME: ${ELASTICSEARCH_CLUSTER_NAME}
      ELASTICSEARCH_CLUSTER_NODES: ${ELASTICSEARCH_CLUSTER_NODES}
      SLEUTH_SAMPLER_PROBABILITY: 1.0
      ZIPKIN_BASE_URL: ${ZIPKIN_BASE_URL}
      ZIPKIN_ENABLED: ${ZIPKIN_ENABLED}
    depends_on:
      - postgres
      - mongo
      - kafka
      - zookeeper

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 6000
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:Latest 
    ports:
      - "2181:2181"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  zipkin:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"

volumes:
  postgres-data:
  mongo-data:
  elasticsearch-data:
